var annotated_dup =
[
    [ "clap", "namespaceclap.html", [
      [ "App", "classclap_1_1App.html", "classclap_1_1App" ],
      [ "ClapException", "classclap_1_1ClapException.html", "classclap_1_1ClapException" ],
      [ "ConfigError", "classclap_1_1ConfigError.html", "classclap_1_1ConfigError" ],
      [ "Flag", "classclap_1_1Flag.html", "classclap_1_1Flag" ],
      [ "HelpRequested", "classclap_1_1HelpRequested.html", "classclap_1_1HelpRequested" ],
      [ "IArgument", "classclap_1_1IArgument.html", "classclap_1_1IArgument" ],
      [ "MissingRequiredArgument", "classclap_1_1MissingRequiredArgument.html", "classclap_1_1MissingRequiredArgument" ],
      [ "MissingValue", "classclap_1_1MissingValue.html", "classclap_1_1MissingValue" ],
      [ "Option", "classclap_1_1Option.html", "classclap_1_1Option" ],
      [ "ParseError", "classclap_1_1ParseError.html", "classclap_1_1ParseError" ],
      [ "ParseValue", "structclap_1_1ParseValue.html", null ],
      [ "Positional", "classclap_1_1Positional.html", "classclap_1_1Positional" ],
      [ "TypeName", "structclap_1_1TypeName.html", null ],
      [ "TypeName< bool >", "structclap_1_1TypeName_3_01bool_01_4.html", null ],
      [ "TypeName< double >", "structclap_1_1TypeName_3_01double_01_4.html", null ],
      [ "TypeName< float >", "structclap_1_1TypeName_3_01float_01_4.html", null ],
      [ "TypeName< int >", "structclap_1_1TypeName_3_01int_01_4.html", null ],
      [ "TypeName< std::string >", "structclap_1_1TypeName_3_01std_1_1string_01_4.html", null ],
      [ "UnknownArgument", "classclap_1_1UnknownArgument.html", "classclap_1_1UnknownArgument" ]
    ] ],
    [ "AABB", "classAABB.html", "classAABB" ],
    [ "ARayMarchedShape", "classARayMarchedShape.html", "classARayMarchedShape" ],
    [ "Args", "structArgs.html", "structArgs" ],
    [ "AShape", "classAShape.html", "classAShape" ],
    [ "Box", "classBox.html", "classBox" ],
    [ "BVHNode", "classBVHNode.html", "classBVHNode" ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "Chessboard", "classChessboard.html", "classChessboard" ],
    [ "ColoredDiffuse", "classColoredDiffuse.html", "classColoredDiffuse" ],
    [ "Cone", "classCone.html", "classCone" ],
    [ "ConfigUtils", "classConfigUtils.html", null ],
    [ "Core", "classCore.html", "classCore" ],
    [ "CubicRoots", "structCubicRoots.html", "structCubicRoots" ],
    [ "CubicSolver", "classCubicSolver.html", null ],
    [ "Cylinder", "classCylinder.html", "classCylinder" ],
    [ "DirectionalLight", "classDirectionalLight.html", "classDirectionalLight" ],
    [ "FileWatcher", "classFileWatcher.html", "classFileWatcher" ],
    [ "HelpDisplay", "classHelpDisplay.html", "classHelpDisplay" ],
    [ "HitRecord", "classHitRecord.html", "classHitRecord" ],
    [ "Hourglass", "classHourglass.html", "classHourglass" ],
    [ "IBoundable", "classIBoundable.html", "classIBoundable" ],
    [ "ILight", "classILight.html", "classILight" ],
    [ "Image", "classImage.html", "classImage" ],
    [ "ImageTexture", "classImageTexture.html", "classImageTexture" ],
    [ "IMaterial", "classIMaterial.html", "classIMaterial" ],
    [ "InotifyEvent", "classInotifyEvent.html", "classInotifyEvent" ],
    [ "InotifyEventReader", "classInotifyEventReader.html", "classInotifyEventReader" ],
    [ "InotifyException", "classInotifyException.html", "classInotifyException" ],
    [ "InotifyInstance", "classInotifyInstance.html", "classInotifyInstance" ],
    [ "InotifyWatch", "classInotifyWatch.html", "classInotifyWatch" ],
    [ "IShape", "classIShape.html", "classIShape" ],
    [ "JuliaSet3D", "classJuliaSet3D.html", "classJuliaSet3D" ],
    [ "Lambertian", "classLambertian.html", "classLambertian" ],
    [ "LightFactory", "classLightFactory.html", null ],
    [ "LimitedCone", "classLimitedCone.html", "classLimitedCone" ],
    [ "LimitedCylinder", "classLimitedCylinder.html", "classLimitedCylinder" ],
    [ "LimitedHourglass", "classLimitedHourglass.html", "classLimitedHourglass" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "MaterialFactory", "classMaterialFactory.html", null ],
    [ "Matrix4x4", "classMatrix4x4.html", "classMatrix4x4" ],
    [ "MengerSponge", "classMengerSponge.html", "classMengerSponge" ],
    [ "Mesh", "classMesh.html", "classMesh" ],
    [ "MeshTriangle", "classMeshTriangle.html", "classMeshTriangle" ],
    [ "MobiusStrip", "classMobiusStrip.html", "classMobiusStrip" ],
    [ "NormalMapped", "classNormalMapped.html", "classNormalMapped" ],
    [ "ObjParser", "classObjParser.html", "classObjParser" ],
    [ "PerlinNoise", "classPerlinNoise.html", "classPerlinNoise" ],
    [ "Phong", "classPhong.html", "classPhong" ],
    [ "PixelBuffer", "structPixelBuffer.html", "structPixelBuffer" ],
    [ "Plane", "classPlane.html", "classPlane" ],
    [ "PluginLoader", "classPluginLoader.html", "classPluginLoader" ],
    [ "PluginManager", "classPluginManager.html", "classPluginManager" ],
    [ "PluginMetadata", "structPluginMetadata.html", "structPluginMetadata" ],
    [ "PointLight", "classPointLight.html", "classPointLight" ],
    [ "ProgressBar", "classProgressBar.html", "classProgressBar" ],
    [ "QuadraticRoots", "structQuadraticRoots.html", "structQuadraticRoots" ],
    [ "QuadraticSolver", "classQuadraticSolver.html", null ],
    [ "QuarticRoots", "structQuarticRoots.html", "structQuarticRoots" ],
    [ "QuarticSolver", "classQuarticSolver.html", null ],
    [ "Ray", "classRay.html", "classRay" ],
    [ "Rectangle", "classRectangle.html", "classRectangle" ],
    [ "Reflective", "classReflective.html", "classReflective" ],
    [ "Refractive", "classRefractive.html", "classRefractive" ],
    [ "RendererConfig", "structRendererConfig.html", "structRendererConfig" ],
    [ "RenderPanel", "classRenderPanel.html", "classRenderPanel" ],
    [ "RenderSampler", "classRenderSampler.html", "classRenderSampler" ],
    [ "RenderStats", "structRenderStats.html", "structRenderStats" ],
    [ "Scene", "classScene.html", "classScene" ],
    [ "SceneBrowser", "classSceneBrowser.html", "classSceneBrowser" ],
    [ "SceneParser", "classSceneParser.html", "classSceneParser" ],
    [ "ShapeFactory", "classShapeFactory.html", null ],
    [ "Sphere", "classSphere.html", "classSphere" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "Tanglecube", "classTanglecube.html", "classTanglecube" ],
    [ "ToastConfig", "structToastConfig.html", "structToastConfig" ],
    [ "ToastManager", "classToastManager.html", "classToastManager" ],
    [ "Torus", "classTorus.html", "classTorus" ],
    [ "Triangle", "classTriangle.html", "classTriangle" ],
    [ "UIApp", "classUIApp.html", "classUIApp" ],
    [ "UV", "structUV.html", "structUV" ],
    [ "Vec3", "classVec3.html", "classVec3" ],
    [ "Vec3C", "structVec3C.html", "structVec3C" ],
    [ "World", "classWorld.html", "classWorld" ]
];